namespace RepoFluent.Application;

public sealed record Block(
    string Type,
    string? Text,
    string? Tone,
    string? Title,
    string? RepositoryId,
    string? Path,
    string? Language,
    int? StartLine,
    int? EndLine,
    string? Symbol,
    string? Explanation,
    string? Description,
    string? AlternativeText,
    IReadOnlyList<string>? Labels,
    string? Branch,
    string? Commit,
    string? Excerpt,
    string? ContentClassification,
    string? Provenance,
    string? Term,
    string? Definition,
    string? Prompt,
    string? AssessmentId,
    string? ResourceUrl,
    IReadOnlyList<CodeTourStep>? Steps);
